name: basic-artifact
on:
    push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: touch output.txt
            - run: echo "artifact successful" >> output.txt
            - uses: actions/upload-artifact@v4
              with:
                name: output-file
                path: output.txt